version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGODB_DATABASE="meetme"
    ports:
      - 27017:27017
    volumes:
      - mongo_db_data_container:/data/db
volumes:
  mongo_db_data_container:
